name: test_core
description: " services package."
version: 0.0.3

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  another_flushbar: ^1.12.30
  dash_chat_2: ^0.0.20
  dio: ^5.4.3+1
  easy_refresh: ^3.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_flavor: ^3.1.3
  flutter_form_builder: ^9.2.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.15.0
  form_builder_validators: ^9.1.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.18.1
  keyboard_dismisser: ^3.0.0
  mixpanel_flutter: ^2.2.0
  package_info_plus: ^8.0.0
  responsive_sizer: ^3.3.1
  sendbird_chat_sdk: ^4.2.14
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  styled_text: ^8.1.0
  widget_mask: ^1.0.0+0
  chewie: ^1.8.0
  flutter_svg_provider: ^1.0.7
  grouped_list: ^6.0.0
  cached_network_image: ^3.3.1
  sprintf: ^7.0.0
  table_calendar: ^3.0.9
  collection: ^1.18.0
  flutter_timezone: ^1.0.8
  file_picker: ^8.0.5
  path: ^1.9.0
  path_provider: ^2.1.3
  webview_flutter: ^4.8.0
  filesize: ^2.0.1
  html: ^0.15.4
  adaptive_dialog: ^2.1.0
  add_2_calendar: ^3.0.1
  image_picker: ^1.1.2
  share_plus: ^10.0.0
  cross_file: ^0.3.4+1
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

